#!/bin/bash

NAME=$1
HEAPSIZE=$2

if [ -z $NAME ]; then
        NAME="default"
fi

if [ -z $HEAPSIZE ]; then
        HEAPSIZE=1
fi

BASE_DIR=.
PIDFILE=$BASE_DIR/structrdb-$NAME.pid
STRUCTR_SCRIPT=$BASE_DIR/run.sh

# run structr script
$STRUCTR_SCRIPT $NAME $HEAPSIZE

