#!/bin/bash

NAME=$1

if [ -z $NAME ]; then
        NAME="default"
fi

BASE_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
PIDFILE=$BASE_DIR/structrdb-$NAME.pid
LOGS_DIR=$BASE_DIR/logs
SERVER_LOG=$BASE_DIR/logs/server.log

start-stop-daemon --stop --signal 15 --pidfile $PIDFILE

rm $PIDFILE
