#!/bin/bash

BASE_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
PIDFILE=$BASE_DIR/structr-ui.pid
LOGS_DIR=$BASE_DIR/logs
SERVER_LOG=$BASE_DIR/logs/server.log

PID=`cat $PIDFILE`
kill -15 $PID

( tail -q -n0 -F $SERVER_LOG & echo $! >tail.pid ) | sed -n '/Shutdown complete/q'

rm $PIDFILE

echo "Structr stopped."
kill `cat tail.pid`
rm tail.pid