#!/bin/bash

cd /opt/structr

VERSION=$1

# no version requested
if [ -z $VERSION ]; then
  echo "No version requested, falling back to default branch"
  VERSION=structrdb-master
else
  echo "Checking out version $VERSION"
fi

git checkout $VERSION
git pull origin $VERSION

mvn -U clean install -DskipTests
cd structr-ui
./stop

sleep 5
rm db/nioneo_logical.log.v*
rm db/index/lucene.log.v*

# make backup
date=`date +%Y%m%d%H%M%S`
cp -a db db-$date
cp -a files files-$date

# start before archiving saves time
./start

tar cvfj db_files-$date.tar.bz2 db-$date files-$date
#mv db_files-$date.tar.bz2 /data/backup/structrdb/
rm -rf db-$date files-$date
