#!/bin/bash

cp \
config_login.png \
config_after-login.png \
config_create-database-connection.png \
config_configure-database-connection.png \
config_database-connection-specified.png \
config_database-connection-wait.png \
config_database-connection-established.png \
login.png \
schema.png \
schema_property-added_projectId.png \
schema_create-type_Project.png \
schema_relationship-project-milestone-created.png \
schema_relationship-project-task-created.png \
schema_create-type_Milestone.png \
schema_added-Milestone-properties.png \
schema_added-Task-properties.png \
data.png \
data_objects-created.png \
data_objects-linked.png \
pages.png \
pages_create-page.png \
pages_page-created.png \
pages_page-expanded.png \
pages_simple-table-added.png \
pages_output-expression.png \
pages_repeater.png \
security.png \
security_create-user.png \
security_rename-user.png \
security_change-admin-password.png \
security_create-group.png \
security_user-dragged-on-group.png \
security_create-resource-access-auth-user-get.png \
security_create-resource-access-auth-user-post.png \
security_create-cors-setting.png \
../../../../structr-base/src/main/resources/structr/docs/1-Introduction/
