#!/bin/bash
JAVA=`which java`
STRUCTR="-jar structr-ui.war"
STRUCTR_ARGS="-Dport=8080 -DhttpsPort=8081 -server -d64 -Xms512m -Xmx512m"

NAME=structr-ui
BASE_DIR=/home/axel/NetBeansProjects/structr/structr/structr-ui
PIDFILE=$BASE_DIR/structr-ui.pid
LOGS_DIR=$BASE_DIR/logs
SERVER_LOG=$BASE_DIR/logs/server.log

if [ -f $BASE_DIR/structr-ui-latest.war ]; then
        mv structr-ui-latest.war structr-ui.war
else
        echo "No newer version found"
fi
cp target/structr-ui.war .
start-stop-daemon --quiet --start --make-pidfile --pidfile $PIDFILE --chdir $BASE_DIR --exec $JAVA -- $STRUCTR_ARGS $STRUCTR >$SERVER_LOG 2>&1 &


