#!/bin/bash
export MAVEN_OPTS="-Xms2g -Xmx2g -XX:+UseNUMA"
mvn exec:java -Dexec.mainClass="org.structr.StructrServer" -Dhost=localhost -Dport=8082
#sleep 10
#xdg-open http://localhost:8082/structr/ &


