#!/bin/bash
#export MAVEN_OPTS="-Xms2g -Xmx2g -XX:+UseNUMA -Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,address=5005,server=y,suspend=n $MAVEN_OPTS"
export MAVEN_OPTS="-Xms1g -Xmx1g -XX:+UseNUMA$MAVEN_OPTS"
mvn exec:java -Dexec.mainClass="org.structr.Ui" -Dexec.args="-classpath target/lib/*:target/structr-ui-0.5.4-SNAPSHOT.jar" 
#sleep 10
#xdg-open http://localhost:8082/structr/ &


