#!/bin/bash

NAME=$1
HEAPSIZE=$2

if [ -z $NAME ]; then
        NAME="default"
fi

if [ -z $HEAPSIZE ]; then
        HEAPSIZE=1
fi

BASE_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $BASE_DIR

PIDFILE=$BASE_DIR/structr-$NAME.pid
SERVER_LOG=$BASE_DIR/logs/server.log

if [ ! -f $PIDFILE ]; then

	echo
	echo "        No Structr server running."
	echo
	
	exit 0
	
fi

SERVER_PID=`cat $PIDFILE`

echo 
echo -n "        Stopping Structr server with pid $SERVER_PID: "

kill -15 $SERVER_PID

( tail -q -n0 -F $SERVER_LOG & echo $! >tail.pid ) | sed -n '/Shutdown complete/q'

rm $PIDFILE
kill `cat tail.pid`
rm tail.pid

echo "OK"
echo
