#!/bin/sh

NAME=$1
HEAPSIZE=$2

if [ -z $NAME ]; then
        NAME="default"
fi

if [ -z $HEAPSIZE ]; then
        HEAPSIZE=1
fi

BASE_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
STRUCTR_SCRIPT=$BASE_DIR/run.sh

$STRUCTR_SCRIPT $NAME $HEAPSIZE
