#!/bin/bash
#cd ../../../../structr-app/target/playwright-screenshots
cd screenshots
cp \
config_set-superuser-password.png \
config_superuser-password-set.png \
config_create-database-connection.png \
config_configure-database-connection.png \
config_database-connection-specified.png \
config_database-connection-wait.png \
config_database-connection-established.png \
login.png \
dashboard_about-me.png \
dashboard_about-structr.png \
dashboard_deployment.png \
dashboard_methods.png \
dashboard_server-log.png \
dashboard_event-log.png \
dashboard_running-threads.png \
dashboard_ui-config.png \
schema.png \
schema_create-type_Project.png \
schema_property-added_projectId.png \
schema_property-added_dueDate.png \
schema_type-created_Project.png \
schema_create-type_Milestone.png \
schema_added-Milestone-properties.png \
schema_type-created_Milestone.png \
schema_relationship-project-milestone-created.png \
schema_added-Task-properties.png \
schema_relationship-project-task-created.png \
data.png \
data_objects-created.png \
data_objects-linked.png \
pages.png \
pages_create-page.png \
pages_page-created.png \
pages_page-expanded.png \
pages_page-preview.png \
pages_simple-table-added.png \
pages_output-expression.png \
pages_repeater.png \
files.png \
files_create-folder.png \
files_navigated-to-folder.png \
files_renamed-folder.png \
security.png \
security_create-user.png \
security_rename-user.png \
security_change-admin-password.png \
security_create-group.png \
security_renamed-group.png \
security_user-dragged-on-group.png \
security_create-resource-access-auth-user-get.png \
security_.png \
security_create-resource-access-auth-user-post.png \
security_create-cors-setting.png \
code.png \
code_create-user-defined-function.png \
code_run-function.png \
code_run-function-result.png \
code_project-to-openapi.png \
flows.png \
flows_created-flow.png \
flows_added-type-query.png \
flows_created-return-node.png \
flows_arranged-nodes.png \
flows_connected-nodes.png \
flows_run-flow.png \
importer.png \
importer_created-file.png \
importer_renamed-file.png \
importer_set-content-type.png \
importer_check-import-process.png \
localization.png \
localization_created.png \
virtual-types.png \
mail-templates.png \
../../../main/resources/structr/docs/
#../../../../main/resources/structr/docs/
