#!/bin/sh
if [ -s structr.pid ]; then

	kill $(cat structr.pid) & # 1> /dev/null 2>&1 &

	sleep 1

	while ! (tail structr.log | grep -qi "Server closed"); do
		#echo "sleeping 1 sec"
		sleep 1
	done

	echo "structr shutdown (pid was: $(cat structr.pid))"
	rm structr.pid

else

	echo "structr doesn't seem to run. There's no pid file 'structr.pid'."

fi


